

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CadParcial2Esa
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class Parcial2EsaEntities1 : DbContext
{
    public Parcial2EsaEntities1()
        : base("name=Parcial2EsaEntities1")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Canal> Canal { get; set; }

    public virtual DbSet<Programa> Programa { get; set; }


    public virtual ObjectResult<paProgramaListar_Result> paProgramaListar(string parametro)
    {

        var parametroParameter = parametro != null ?
            new ObjectParameter("parametro", parametro) :
            new ObjectParameter("parametro", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paProgramaListar_Result>("paProgramaListar", parametroParameter);
    }

}

}

